#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

GREEN='\033[0;32m'
NOCOLOR='\033[0m'

echo "${GREEN}Starting pre-commit hook${NOCOLOR}"

echo "${GREEN}### Checking staged files...${NOCOLOR}"
npx lint-staged --verbose

echo "${GREEN}### Checking types...${NOCOLOR}"
npm run typecheck

echo "${GREEN}### Auditing dependencies...${NOCOLOR}"
npm run audit

echo "${GREEN}Finished pre-commit hook${NOCOLOR}"


