name: Quality checks

on:
  pull_request:
    branches:
      - main

jobs:
  sanity-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/dist/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 20

      - name: Install
        run: npm ci

      - name: Security Audits
        run: npm run audit -- --production

      - name: Run Lint
        run: npm run lint

      - name: Run Prettier Check
        run: npm run prettier-check

      - name: Run Unit Tests
        run: npm run test

      - name: Build
        run: npm run build

      - name: Run Unit tests
        run: |
          npx jest --ci --collectCoverage --shard=${{ matrix.shard }}/${{ strategy.job-total }}
