name: Publish to Github Packages

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install deps
        run: npm ci
      
      - name: Security Audits
        run: npm run audit -- --production

      - name: Build & publish
        run: |
          npm run build
          cp .npmrc ./dist
          cp package.json ./dist && cd dist
          npm publish
  